import { AgregarComentarioComandaData, AgregarComentarioComandaVariables, ResolverMiIncidenciaData, ResolverMiIncidenciaVariables, AutoAsignarComandaOperarioData, AutoAsignarComandaOperarioVariables, GetComandaDetalleOperarioData, GetComandaDetalleOperarioVariables, GetMisComandasAsignadasData, GetMisComandasAsignadasVariables, CrearAvisoData, CrearAvisoVariables, GetAvisosAdministracionData, GetAvisosAdministracionVariables, GetAvisosParaEquipoData, GetAvisosParaEquipoVariables, RegistrarseData, RegistrarseVariables, CrearUsuarioAdministradoData, CrearUsuarioAdministradoVariables, RegistrarseComoClienteData, RegistrarseComoClienteVariables, CrearClienteAdministradoData, CrearClienteAdministradoVariables, ActualizarUsuarioData, ActualizarUsuarioVariables, CrearVehiculoData, CrearVehiculoVariables, ActualizarVehiculoData, ActualizarVehiculoVariables, CrearSalidaVehiculoData, CrearSalidaVehiculoVariables, RegistrarInspeccionAntesData, RegistrarInspeccionAntesVariables, IniciarSalidaVehiculoData, IniciarSalidaVehiculoVariables, RegistrarInspeccionDespuesData, RegistrarInspeccionDespuesVariables, AgregarFotoInspeccionVehiculoData, AgregarFotoInspeccionVehiculoVariables, CrearClienteComandaData, CrearClienteComandaVariables, EditarFichaClienteData, EditarFichaClienteVariables, CrearComandaData, CrearComandaVariables, AgregarComandaDetalleData, AgregarComandaDetalleVariables, AnularComandaData, AnularComandaVariables, EntregarComandaData, EntregarComandaVariables, EditarComandaData, EditarComandaVariables, EliminarDetallesComandaData, EliminarDetallesComandaVariables, CrearTipoPrendaData, CrearTipoPrendaVariables, CrearTipoServicioData, CrearTipoServicioVariables, CrearInsumoData, CrearInsumoVariables, ActualizarInsumoData, ActualizarInsumoVariables, RegistrarEntradaInventarioData, RegistrarEntradaInventarioVariables, RegistrarSalidaInventarioData, RegistrarSalidaInventarioVariables, AsociarFlujoComandaPendienteData, AsociarFlujoComandaPendienteVariables, ConfigurarEtapaProduccionData, ConfigurarEtapaProduccionVariables, ConfigurarLimitesEtapasData, ConfigurarLimitesEtapasVariables, CompletarEtapaComandaData, CompletarEtapaComandaVariables, RegistrarIncidenciaComandaData, RegistrarIncidenciaComandaVariables, ActualizarEstadoIncidenciaData, ActualizarEstadoIncidenciaVariables, ReasignarOperarioEtapaData, ReasignarOperarioEtapaVariables, GetEtapasProduccionData, GetSeguimientoProduccionData, GetSeguimientoProduccionVariables, GetPanelProduccionData, GetPanelProduccionVariables, GetComandasParaAlertasData, GetComandasParaAlertasVariables, GetIncidenciasData, GetMiComandaGuardadaData, GetMiComandaGuardadaVariables, GetRolesData, GetMiPerfilData, GetUsuariosData, GetComandaPorQrData, GetComandaPorQrVariables, GetInsumoPorQrData, GetInsumoPorQrVariables, GetInventarioData, GetVehiculosData, GetMisSalidasVehiculoData, GetComandasPaginadasData, GetComandasPaginadasVariables, GetComandasActivasCountData, GetComandaDetalleData, GetComandaDetalleVariables, GetCatalogosComandaData, DiagnosticoComandasData, GetFichasClientesData, GetReporteCuentasData, GetReporteCuentasVariables, GetDetalleReporteCuentasData, GetDetalleReporteCuentasVariables, GetFiltrosReportesData, GetFiltrosReportesVariables, GetSeguimientoPublicoPorQrData, GetSeguimientoPublicoPorQrVariables, GetSeguimientoPublicoPorNumeroData, GetSeguimientoPublicoPorNumeroVariables, GetComandaOperativaPorQrData, GetComandaOperativaPorQrVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useAgregarComentarioComanda(options?: useDataConnectMutationOptions<AgregarComentarioComandaData, FirebaseError, AgregarComentarioComandaVariables>): UseDataConnectMutationResult<AgregarComentarioComandaData, AgregarComentarioComandaVariables>;
export function useAgregarComentarioComanda(dc: DataConnect, options?: useDataConnectMutationOptions<AgregarComentarioComandaData, FirebaseError, AgregarComentarioComandaVariables>): UseDataConnectMutationResult<AgregarComentarioComandaData, AgregarComentarioComandaVariables>;

export function useResolverMiIncidencia(options?: useDataConnectMutationOptions<ResolverMiIncidenciaData, FirebaseError, ResolverMiIncidenciaVariables>): UseDataConnectMutationResult<ResolverMiIncidenciaData, ResolverMiIncidenciaVariables>;
export function useResolverMiIncidencia(dc: DataConnect, options?: useDataConnectMutationOptions<ResolverMiIncidenciaData, FirebaseError, ResolverMiIncidenciaVariables>): UseDataConnectMutationResult<ResolverMiIncidenciaData, ResolverMiIncidenciaVariables>;

export function useAutoAsignarComandaOperario(options?: useDataConnectMutationOptions<AutoAsignarComandaOperarioData, FirebaseError, AutoAsignarComandaOperarioVariables>): UseDataConnectMutationResult<AutoAsignarComandaOperarioData, AutoAsignarComandaOperarioVariables>;
export function useAutoAsignarComandaOperario(dc: DataConnect, options?: useDataConnectMutationOptions<AutoAsignarComandaOperarioData, FirebaseError, AutoAsignarComandaOperarioVariables>): UseDataConnectMutationResult<AutoAsignarComandaOperarioData, AutoAsignarComandaOperarioVariables>;

export function useGetComandaDetalleOperario(vars: GetComandaDetalleOperarioVariables, options?: useDataConnectQueryOptions<GetComandaDetalleOperarioData>): UseDataConnectQueryResult<GetComandaDetalleOperarioData, GetComandaDetalleOperarioVariables>;
export function useGetComandaDetalleOperario(dc: DataConnect, vars: GetComandaDetalleOperarioVariables, options?: useDataConnectQueryOptions<GetComandaDetalleOperarioData>): UseDataConnectQueryResult<GetComandaDetalleOperarioData, GetComandaDetalleOperarioVariables>;

export function useGetMisComandasAsignadas(vars?: GetMisComandasAsignadasVariables, options?: useDataConnectQueryOptions<GetMisComandasAsignadasData>): UseDataConnectQueryResult<GetMisComandasAsignadasData, GetMisComandasAsignadasVariables>;
export function useGetMisComandasAsignadas(dc: DataConnect, vars?: GetMisComandasAsignadasVariables, options?: useDataConnectQueryOptions<GetMisComandasAsignadasData>): UseDataConnectQueryResult<GetMisComandasAsignadasData, GetMisComandasAsignadasVariables>;

export function useCrearAviso(options?: useDataConnectMutationOptions<CrearAvisoData, FirebaseError, CrearAvisoVariables>): UseDataConnectMutationResult<CrearAvisoData, CrearAvisoVariables>;
export function useCrearAviso(dc: DataConnect, options?: useDataConnectMutationOptions<CrearAvisoData, FirebaseError, CrearAvisoVariables>): UseDataConnectMutationResult<CrearAvisoData, CrearAvisoVariables>;

export function useGetAvisosAdministracion(vars?: GetAvisosAdministracionVariables, options?: useDataConnectQueryOptions<GetAvisosAdministracionData>): UseDataConnectQueryResult<GetAvisosAdministracionData, GetAvisosAdministracionVariables>;
export function useGetAvisosAdministracion(dc: DataConnect, vars?: GetAvisosAdministracionVariables, options?: useDataConnectQueryOptions<GetAvisosAdministracionData>): UseDataConnectQueryResult<GetAvisosAdministracionData, GetAvisosAdministracionVariables>;

export function useGetAvisosParaEquipo(vars: GetAvisosParaEquipoVariables, options?: useDataConnectQueryOptions<GetAvisosParaEquipoData>): UseDataConnectQueryResult<GetAvisosParaEquipoData, GetAvisosParaEquipoVariables>;
export function useGetAvisosParaEquipo(dc: DataConnect, vars: GetAvisosParaEquipoVariables, options?: useDataConnectQueryOptions<GetAvisosParaEquipoData>): UseDataConnectQueryResult<GetAvisosParaEquipoData, GetAvisosParaEquipoVariables>;

export function useRegistrarse(options?: useDataConnectMutationOptions<RegistrarseData, FirebaseError, RegistrarseVariables>): UseDataConnectMutationResult<RegistrarseData, RegistrarseVariables>;
export function useRegistrarse(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarseData, FirebaseError, RegistrarseVariables>): UseDataConnectMutationResult<RegistrarseData, RegistrarseVariables>;

export function useCrearUsuarioAdministrado(options?: useDataConnectMutationOptions<CrearUsuarioAdministradoData, FirebaseError, CrearUsuarioAdministradoVariables>): UseDataConnectMutationResult<CrearUsuarioAdministradoData, CrearUsuarioAdministradoVariables>;
export function useCrearUsuarioAdministrado(dc: DataConnect, options?: useDataConnectMutationOptions<CrearUsuarioAdministradoData, FirebaseError, CrearUsuarioAdministradoVariables>): UseDataConnectMutationResult<CrearUsuarioAdministradoData, CrearUsuarioAdministradoVariables>;

export function useRegistrarseComoCliente(options?: useDataConnectMutationOptions<RegistrarseComoClienteData, FirebaseError, RegistrarseComoClienteVariables>): UseDataConnectMutationResult<RegistrarseComoClienteData, RegistrarseComoClienteVariables>;
export function useRegistrarseComoCliente(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarseComoClienteData, FirebaseError, RegistrarseComoClienteVariables>): UseDataConnectMutationResult<RegistrarseComoClienteData, RegistrarseComoClienteVariables>;

export function useCrearClienteAdministrado(options?: useDataConnectMutationOptions<CrearClienteAdministradoData, FirebaseError, CrearClienteAdministradoVariables>): UseDataConnectMutationResult<CrearClienteAdministradoData, CrearClienteAdministradoVariables>;
export function useCrearClienteAdministrado(dc: DataConnect, options?: useDataConnectMutationOptions<CrearClienteAdministradoData, FirebaseError, CrearClienteAdministradoVariables>): UseDataConnectMutationResult<CrearClienteAdministradoData, CrearClienteAdministradoVariables>;

export function useActualizarUsuario(options?: useDataConnectMutationOptions<ActualizarUsuarioData, FirebaseError, ActualizarUsuarioVariables>): UseDataConnectMutationResult<ActualizarUsuarioData, ActualizarUsuarioVariables>;
export function useActualizarUsuario(dc: DataConnect, options?: useDataConnectMutationOptions<ActualizarUsuarioData, FirebaseError, ActualizarUsuarioVariables>): UseDataConnectMutationResult<ActualizarUsuarioData, ActualizarUsuarioVariables>;

export function useCrearVehiculo(options?: useDataConnectMutationOptions<CrearVehiculoData, FirebaseError, CrearVehiculoVariables>): UseDataConnectMutationResult<CrearVehiculoData, CrearVehiculoVariables>;
export function useCrearVehiculo(dc: DataConnect, options?: useDataConnectMutationOptions<CrearVehiculoData, FirebaseError, CrearVehiculoVariables>): UseDataConnectMutationResult<CrearVehiculoData, CrearVehiculoVariables>;

export function useActualizarVehiculo(options?: useDataConnectMutationOptions<ActualizarVehiculoData, FirebaseError, ActualizarVehiculoVariables>): UseDataConnectMutationResult<ActualizarVehiculoData, ActualizarVehiculoVariables>;
export function useActualizarVehiculo(dc: DataConnect, options?: useDataConnectMutationOptions<ActualizarVehiculoData, FirebaseError, ActualizarVehiculoVariables>): UseDataConnectMutationResult<ActualizarVehiculoData, ActualizarVehiculoVariables>;

export function useCrearSalidaVehiculo(options?: useDataConnectMutationOptions<CrearSalidaVehiculoData, FirebaseError, CrearSalidaVehiculoVariables>): UseDataConnectMutationResult<CrearSalidaVehiculoData, CrearSalidaVehiculoVariables>;
export function useCrearSalidaVehiculo(dc: DataConnect, options?: useDataConnectMutationOptions<CrearSalidaVehiculoData, FirebaseError, CrearSalidaVehiculoVariables>): UseDataConnectMutationResult<CrearSalidaVehiculoData, CrearSalidaVehiculoVariables>;

export function useRegistrarInspeccionAntes(options?: useDataConnectMutationOptions<RegistrarInspeccionAntesData, FirebaseError, RegistrarInspeccionAntesVariables>): UseDataConnectMutationResult<RegistrarInspeccionAntesData, RegistrarInspeccionAntesVariables>;
export function useRegistrarInspeccionAntes(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarInspeccionAntesData, FirebaseError, RegistrarInspeccionAntesVariables>): UseDataConnectMutationResult<RegistrarInspeccionAntesData, RegistrarInspeccionAntesVariables>;

export function useIniciarSalidaVehiculo(options?: useDataConnectMutationOptions<IniciarSalidaVehiculoData, FirebaseError, IniciarSalidaVehiculoVariables>): UseDataConnectMutationResult<IniciarSalidaVehiculoData, IniciarSalidaVehiculoVariables>;
export function useIniciarSalidaVehiculo(dc: DataConnect, options?: useDataConnectMutationOptions<IniciarSalidaVehiculoData, FirebaseError, IniciarSalidaVehiculoVariables>): UseDataConnectMutationResult<IniciarSalidaVehiculoData, IniciarSalidaVehiculoVariables>;

export function useRegistrarInspeccionDespues(options?: useDataConnectMutationOptions<RegistrarInspeccionDespuesData, FirebaseError, RegistrarInspeccionDespuesVariables>): UseDataConnectMutationResult<RegistrarInspeccionDespuesData, RegistrarInspeccionDespuesVariables>;
export function useRegistrarInspeccionDespues(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarInspeccionDespuesData, FirebaseError, RegistrarInspeccionDespuesVariables>): UseDataConnectMutationResult<RegistrarInspeccionDespuesData, RegistrarInspeccionDespuesVariables>;

export function useAgregarFotoInspeccionVehiculo(options?: useDataConnectMutationOptions<AgregarFotoInspeccionVehiculoData, FirebaseError, AgregarFotoInspeccionVehiculoVariables>): UseDataConnectMutationResult<AgregarFotoInspeccionVehiculoData, AgregarFotoInspeccionVehiculoVariables>;
export function useAgregarFotoInspeccionVehiculo(dc: DataConnect, options?: useDataConnectMutationOptions<AgregarFotoInspeccionVehiculoData, FirebaseError, AgregarFotoInspeccionVehiculoVariables>): UseDataConnectMutationResult<AgregarFotoInspeccionVehiculoData, AgregarFotoInspeccionVehiculoVariables>;

export function useCrearClienteComanda(options?: useDataConnectMutationOptions<CrearClienteComandaData, FirebaseError, CrearClienteComandaVariables>): UseDataConnectMutationResult<CrearClienteComandaData, CrearClienteComandaVariables>;
export function useCrearClienteComanda(dc: DataConnect, options?: useDataConnectMutationOptions<CrearClienteComandaData, FirebaseError, CrearClienteComandaVariables>): UseDataConnectMutationResult<CrearClienteComandaData, CrearClienteComandaVariables>;

export function useEditarFichaCliente(options?: useDataConnectMutationOptions<EditarFichaClienteData, FirebaseError, EditarFichaClienteVariables>): UseDataConnectMutationResult<EditarFichaClienteData, EditarFichaClienteVariables>;
export function useEditarFichaCliente(dc: DataConnect, options?: useDataConnectMutationOptions<EditarFichaClienteData, FirebaseError, EditarFichaClienteVariables>): UseDataConnectMutationResult<EditarFichaClienteData, EditarFichaClienteVariables>;

export function useCrearComanda(options?: useDataConnectMutationOptions<CrearComandaData, FirebaseError, CrearComandaVariables>): UseDataConnectMutationResult<CrearComandaData, CrearComandaVariables>;
export function useCrearComanda(dc: DataConnect, options?: useDataConnectMutationOptions<CrearComandaData, FirebaseError, CrearComandaVariables>): UseDataConnectMutationResult<CrearComandaData, CrearComandaVariables>;

export function useAgregarComandaDetalle(options?: useDataConnectMutationOptions<AgregarComandaDetalleData, FirebaseError, AgregarComandaDetalleVariables>): UseDataConnectMutationResult<AgregarComandaDetalleData, AgregarComandaDetalleVariables>;
export function useAgregarComandaDetalle(dc: DataConnect, options?: useDataConnectMutationOptions<AgregarComandaDetalleData, FirebaseError, AgregarComandaDetalleVariables>): UseDataConnectMutationResult<AgregarComandaDetalleData, AgregarComandaDetalleVariables>;

export function useAnularComanda(options?: useDataConnectMutationOptions<AnularComandaData, FirebaseError, AnularComandaVariables>): UseDataConnectMutationResult<AnularComandaData, AnularComandaVariables>;
export function useAnularComanda(dc: DataConnect, options?: useDataConnectMutationOptions<AnularComandaData, FirebaseError, AnularComandaVariables>): UseDataConnectMutationResult<AnularComandaData, AnularComandaVariables>;

export function useEntregarComanda(options?: useDataConnectMutationOptions<EntregarComandaData, FirebaseError, EntregarComandaVariables>): UseDataConnectMutationResult<EntregarComandaData, EntregarComandaVariables>;
export function useEntregarComanda(dc: DataConnect, options?: useDataConnectMutationOptions<EntregarComandaData, FirebaseError, EntregarComandaVariables>): UseDataConnectMutationResult<EntregarComandaData, EntregarComandaVariables>;

export function useEditarComanda(options?: useDataConnectMutationOptions<EditarComandaData, FirebaseError, EditarComandaVariables>): UseDataConnectMutationResult<EditarComandaData, EditarComandaVariables>;
export function useEditarComanda(dc: DataConnect, options?: useDataConnectMutationOptions<EditarComandaData, FirebaseError, EditarComandaVariables>): UseDataConnectMutationResult<EditarComandaData, EditarComandaVariables>;

export function useEliminarDetallesComanda(options?: useDataConnectMutationOptions<EliminarDetallesComandaData, FirebaseError, EliminarDetallesComandaVariables>): UseDataConnectMutationResult<EliminarDetallesComandaData, EliminarDetallesComandaVariables>;
export function useEliminarDetallesComanda(dc: DataConnect, options?: useDataConnectMutationOptions<EliminarDetallesComandaData, FirebaseError, EliminarDetallesComandaVariables>): UseDataConnectMutationResult<EliminarDetallesComandaData, EliminarDetallesComandaVariables>;

export function useCrearTipoPrenda(options?: useDataConnectMutationOptions<CrearTipoPrendaData, FirebaseError, CrearTipoPrendaVariables>): UseDataConnectMutationResult<CrearTipoPrendaData, CrearTipoPrendaVariables>;
export function useCrearTipoPrenda(dc: DataConnect, options?: useDataConnectMutationOptions<CrearTipoPrendaData, FirebaseError, CrearTipoPrendaVariables>): UseDataConnectMutationResult<CrearTipoPrendaData, CrearTipoPrendaVariables>;

export function useCrearTipoServicio(options?: useDataConnectMutationOptions<CrearTipoServicioData, FirebaseError, CrearTipoServicioVariables>): UseDataConnectMutationResult<CrearTipoServicioData, CrearTipoServicioVariables>;
export function useCrearTipoServicio(dc: DataConnect, options?: useDataConnectMutationOptions<CrearTipoServicioData, FirebaseError, CrearTipoServicioVariables>): UseDataConnectMutationResult<CrearTipoServicioData, CrearTipoServicioVariables>;

export function useCrearInsumo(options?: useDataConnectMutationOptions<CrearInsumoData, FirebaseError, CrearInsumoVariables>): UseDataConnectMutationResult<CrearInsumoData, CrearInsumoVariables>;
export function useCrearInsumo(dc: DataConnect, options?: useDataConnectMutationOptions<CrearInsumoData, FirebaseError, CrearInsumoVariables>): UseDataConnectMutationResult<CrearInsumoData, CrearInsumoVariables>;

export function useActualizarInsumo(options?: useDataConnectMutationOptions<ActualizarInsumoData, FirebaseError, ActualizarInsumoVariables>): UseDataConnectMutationResult<ActualizarInsumoData, ActualizarInsumoVariables>;
export function useActualizarInsumo(dc: DataConnect, options?: useDataConnectMutationOptions<ActualizarInsumoData, FirebaseError, ActualizarInsumoVariables>): UseDataConnectMutationResult<ActualizarInsumoData, ActualizarInsumoVariables>;

export function useRegistrarEntradaInventario(options?: useDataConnectMutationOptions<RegistrarEntradaInventarioData, FirebaseError, RegistrarEntradaInventarioVariables>): UseDataConnectMutationResult<RegistrarEntradaInventarioData, RegistrarEntradaInventarioVariables>;
export function useRegistrarEntradaInventario(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarEntradaInventarioData, FirebaseError, RegistrarEntradaInventarioVariables>): UseDataConnectMutationResult<RegistrarEntradaInventarioData, RegistrarEntradaInventarioVariables>;

export function useRegistrarSalidaInventario(options?: useDataConnectMutationOptions<RegistrarSalidaInventarioData, FirebaseError, RegistrarSalidaInventarioVariables>): UseDataConnectMutationResult<RegistrarSalidaInventarioData, RegistrarSalidaInventarioVariables>;
export function useRegistrarSalidaInventario(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarSalidaInventarioData, FirebaseError, RegistrarSalidaInventarioVariables>): UseDataConnectMutationResult<RegistrarSalidaInventarioData, RegistrarSalidaInventarioVariables>;

export function useAsociarFlujoComandaPendiente(options?: useDataConnectMutationOptions<AsociarFlujoComandaPendienteData, FirebaseError, AsociarFlujoComandaPendienteVariables>): UseDataConnectMutationResult<AsociarFlujoComandaPendienteData, AsociarFlujoComandaPendienteVariables>;
export function useAsociarFlujoComandaPendiente(dc: DataConnect, options?: useDataConnectMutationOptions<AsociarFlujoComandaPendienteData, FirebaseError, AsociarFlujoComandaPendienteVariables>): UseDataConnectMutationResult<AsociarFlujoComandaPendienteData, AsociarFlujoComandaPendienteVariables>;

export function useConfigurarEtapaProduccion(options?: useDataConnectMutationOptions<ConfigurarEtapaProduccionData, FirebaseError, ConfigurarEtapaProduccionVariables>): UseDataConnectMutationResult<ConfigurarEtapaProduccionData, ConfigurarEtapaProduccionVariables>;
export function useConfigurarEtapaProduccion(dc: DataConnect, options?: useDataConnectMutationOptions<ConfigurarEtapaProduccionData, FirebaseError, ConfigurarEtapaProduccionVariables>): UseDataConnectMutationResult<ConfigurarEtapaProduccionData, ConfigurarEtapaProduccionVariables>;

export function useConfigurarLimitesEtapas(options?: useDataConnectMutationOptions<ConfigurarLimitesEtapasData, FirebaseError, ConfigurarLimitesEtapasVariables>): UseDataConnectMutationResult<ConfigurarLimitesEtapasData, ConfigurarLimitesEtapasVariables>;
export function useConfigurarLimitesEtapas(dc: DataConnect, options?: useDataConnectMutationOptions<ConfigurarLimitesEtapasData, FirebaseError, ConfigurarLimitesEtapasVariables>): UseDataConnectMutationResult<ConfigurarLimitesEtapasData, ConfigurarLimitesEtapasVariables>;

export function useCompletarEtapaComanda(options?: useDataConnectMutationOptions<CompletarEtapaComandaData, FirebaseError, CompletarEtapaComandaVariables>): UseDataConnectMutationResult<CompletarEtapaComandaData, CompletarEtapaComandaVariables>;
export function useCompletarEtapaComanda(dc: DataConnect, options?: useDataConnectMutationOptions<CompletarEtapaComandaData, FirebaseError, CompletarEtapaComandaVariables>): UseDataConnectMutationResult<CompletarEtapaComandaData, CompletarEtapaComandaVariables>;

export function useRegistrarIncidenciaComanda(options?: useDataConnectMutationOptions<RegistrarIncidenciaComandaData, FirebaseError, RegistrarIncidenciaComandaVariables>): UseDataConnectMutationResult<RegistrarIncidenciaComandaData, RegistrarIncidenciaComandaVariables>;
export function useRegistrarIncidenciaComanda(dc: DataConnect, options?: useDataConnectMutationOptions<RegistrarIncidenciaComandaData, FirebaseError, RegistrarIncidenciaComandaVariables>): UseDataConnectMutationResult<RegistrarIncidenciaComandaData, RegistrarIncidenciaComandaVariables>;

export function useActualizarEstadoIncidencia(options?: useDataConnectMutationOptions<ActualizarEstadoIncidenciaData, FirebaseError, ActualizarEstadoIncidenciaVariables>): UseDataConnectMutationResult<ActualizarEstadoIncidenciaData, ActualizarEstadoIncidenciaVariables>;
export function useActualizarEstadoIncidencia(dc: DataConnect, options?: useDataConnectMutationOptions<ActualizarEstadoIncidenciaData, FirebaseError, ActualizarEstadoIncidenciaVariables>): UseDataConnectMutationResult<ActualizarEstadoIncidenciaData, ActualizarEstadoIncidenciaVariables>;

export function useReasignarOperarioEtapa(options?: useDataConnectMutationOptions<ReasignarOperarioEtapaData, FirebaseError, ReasignarOperarioEtapaVariables>): UseDataConnectMutationResult<ReasignarOperarioEtapaData, ReasignarOperarioEtapaVariables>;
export function useReasignarOperarioEtapa(dc: DataConnect, options?: useDataConnectMutationOptions<ReasignarOperarioEtapaData, FirebaseError, ReasignarOperarioEtapaVariables>): UseDataConnectMutationResult<ReasignarOperarioEtapaData, ReasignarOperarioEtapaVariables>;

export function useGetEtapasProduccion(options?: useDataConnectQueryOptions<GetEtapasProduccionData>): UseDataConnectQueryResult<GetEtapasProduccionData, undefined>;
export function useGetEtapasProduccion(dc: DataConnect, options?: useDataConnectQueryOptions<GetEtapasProduccionData>): UseDataConnectQueryResult<GetEtapasProduccionData, undefined>;

export function useGetSeguimientoProduccion(vars?: GetSeguimientoProduccionVariables, options?: useDataConnectQueryOptions<GetSeguimientoProduccionData>): UseDataConnectQueryResult<GetSeguimientoProduccionData, GetSeguimientoProduccionVariables>;
export function useGetSeguimientoProduccion(dc: DataConnect, vars?: GetSeguimientoProduccionVariables, options?: useDataConnectQueryOptions<GetSeguimientoProduccionData>): UseDataConnectQueryResult<GetSeguimientoProduccionData, GetSeguimientoProduccionVariables>;

export function useGetPanelProduccion(vars?: GetPanelProduccionVariables, options?: useDataConnectQueryOptions<GetPanelProduccionData>): UseDataConnectQueryResult<GetPanelProduccionData, GetPanelProduccionVariables>;
export function useGetPanelProduccion(dc: DataConnect, vars?: GetPanelProduccionVariables, options?: useDataConnectQueryOptions<GetPanelProduccionData>): UseDataConnectQueryResult<GetPanelProduccionData, GetPanelProduccionVariables>;

export function useGetComandasParaAlertas(vars?: GetComandasParaAlertasVariables, options?: useDataConnectQueryOptions<GetComandasParaAlertasData>): UseDataConnectQueryResult<GetComandasParaAlertasData, GetComandasParaAlertasVariables>;
export function useGetComandasParaAlertas(dc: DataConnect, vars?: GetComandasParaAlertasVariables, options?: useDataConnectQueryOptions<GetComandasParaAlertasData>): UseDataConnectQueryResult<GetComandasParaAlertasData, GetComandasParaAlertasVariables>;

export function useGetIncidencias(options?: useDataConnectQueryOptions<GetIncidenciasData>): UseDataConnectQueryResult<GetIncidenciasData, undefined>;
export function useGetIncidencias(dc: DataConnect, options?: useDataConnectQueryOptions<GetIncidenciasData>): UseDataConnectQueryResult<GetIncidenciasData, undefined>;

export function useGetMiComandaGuardada(vars: GetMiComandaGuardadaVariables, options?: useDataConnectQueryOptions<GetMiComandaGuardadaData>): UseDataConnectQueryResult<GetMiComandaGuardadaData, GetMiComandaGuardadaVariables>;
export function useGetMiComandaGuardada(dc: DataConnect, vars: GetMiComandaGuardadaVariables, options?: useDataConnectQueryOptions<GetMiComandaGuardadaData>): UseDataConnectQueryResult<GetMiComandaGuardadaData, GetMiComandaGuardadaVariables>;

export function useGetRoles(options?: useDataConnectQueryOptions<GetRolesData>): UseDataConnectQueryResult<GetRolesData, undefined>;
export function useGetRoles(dc: DataConnect, options?: useDataConnectQueryOptions<GetRolesData>): UseDataConnectQueryResult<GetRolesData, undefined>;

export function useGetMiPerfil(options?: useDataConnectQueryOptions<GetMiPerfilData>): UseDataConnectQueryResult<GetMiPerfilData, undefined>;
export function useGetMiPerfil(dc: DataConnect, options?: useDataConnectQueryOptions<GetMiPerfilData>): UseDataConnectQueryResult<GetMiPerfilData, undefined>;

export function useGetUsuarios(options?: useDataConnectQueryOptions<GetUsuariosData>): UseDataConnectQueryResult<GetUsuariosData, undefined>;
export function useGetUsuarios(dc: DataConnect, options?: useDataConnectQueryOptions<GetUsuariosData>): UseDataConnectQueryResult<GetUsuariosData, undefined>;

export function useGetComandaPorQr(vars: GetComandaPorQrVariables, options?: useDataConnectQueryOptions<GetComandaPorQrData>): UseDataConnectQueryResult<GetComandaPorQrData, GetComandaPorQrVariables>;
export function useGetComandaPorQr(dc: DataConnect, vars: GetComandaPorQrVariables, options?: useDataConnectQueryOptions<GetComandaPorQrData>): UseDataConnectQueryResult<GetComandaPorQrData, GetComandaPorQrVariables>;

export function useGetInsumoPorQr(vars: GetInsumoPorQrVariables, options?: useDataConnectQueryOptions<GetInsumoPorQrData>): UseDataConnectQueryResult<GetInsumoPorQrData, GetInsumoPorQrVariables>;
export function useGetInsumoPorQr(dc: DataConnect, vars: GetInsumoPorQrVariables, options?: useDataConnectQueryOptions<GetInsumoPorQrData>): UseDataConnectQueryResult<GetInsumoPorQrData, GetInsumoPorQrVariables>;

export function useGetInventario(options?: useDataConnectQueryOptions<GetInventarioData>): UseDataConnectQueryResult<GetInventarioData, undefined>;
export function useGetInventario(dc: DataConnect, options?: useDataConnectQueryOptions<GetInventarioData>): UseDataConnectQueryResult<GetInventarioData, undefined>;

export function useGetVehiculos(options?: useDataConnectQueryOptions<GetVehiculosData>): UseDataConnectQueryResult<GetVehiculosData, undefined>;
export function useGetVehiculos(dc: DataConnect, options?: useDataConnectQueryOptions<GetVehiculosData>): UseDataConnectQueryResult<GetVehiculosData, undefined>;

export function useGetMisSalidasVehiculo(options?: useDataConnectQueryOptions<GetMisSalidasVehiculoData>): UseDataConnectQueryResult<GetMisSalidasVehiculoData, undefined>;
export function useGetMisSalidasVehiculo(dc: DataConnect, options?: useDataConnectQueryOptions<GetMisSalidasVehiculoData>): UseDataConnectQueryResult<GetMisSalidasVehiculoData, undefined>;

export function useGetComandasPaginadas(vars?: GetComandasPaginadasVariables, options?: useDataConnectQueryOptions<GetComandasPaginadasData>): UseDataConnectQueryResult<GetComandasPaginadasData, GetComandasPaginadasVariables>;
export function useGetComandasPaginadas(dc: DataConnect, vars?: GetComandasPaginadasVariables, options?: useDataConnectQueryOptions<GetComandasPaginadasData>): UseDataConnectQueryResult<GetComandasPaginadasData, GetComandasPaginadasVariables>;

export function useGetComandasActivasCount(options?: useDataConnectQueryOptions<GetComandasActivasCountData>): UseDataConnectQueryResult<GetComandasActivasCountData, undefined>;
export function useGetComandasActivasCount(dc: DataConnect, options?: useDataConnectQueryOptions<GetComandasActivasCountData>): UseDataConnectQueryResult<GetComandasActivasCountData, undefined>;

export function useGetComandaDetalle(vars: GetComandaDetalleVariables, options?: useDataConnectQueryOptions<GetComandaDetalleData>): UseDataConnectQueryResult<GetComandaDetalleData, GetComandaDetalleVariables>;
export function useGetComandaDetalle(dc: DataConnect, vars: GetComandaDetalleVariables, options?: useDataConnectQueryOptions<GetComandaDetalleData>): UseDataConnectQueryResult<GetComandaDetalleData, GetComandaDetalleVariables>;

export function useGetCatalogosComanda(options?: useDataConnectQueryOptions<GetCatalogosComandaData>): UseDataConnectQueryResult<GetCatalogosComandaData, undefined>;
export function useGetCatalogosComanda(dc: DataConnect, options?: useDataConnectQueryOptions<GetCatalogosComandaData>): UseDataConnectQueryResult<GetCatalogosComandaData, undefined>;

export function useDiagnosticoComandas(options?: useDataConnectQueryOptions<DiagnosticoComandasData>): UseDataConnectQueryResult<DiagnosticoComandasData, undefined>;
export function useDiagnosticoComandas(dc: DataConnect, options?: useDataConnectQueryOptions<DiagnosticoComandasData>): UseDataConnectQueryResult<DiagnosticoComandasData, undefined>;

export function useGetFichasClientes(options?: useDataConnectQueryOptions<GetFichasClientesData>): UseDataConnectQueryResult<GetFichasClientesData, undefined>;
export function useGetFichasClientes(dc: DataConnect, options?: useDataConnectQueryOptions<GetFichasClientesData>): UseDataConnectQueryResult<GetFichasClientesData, undefined>;

export function useGetReporteCuentas(vars: GetReporteCuentasVariables, options?: useDataConnectQueryOptions<GetReporteCuentasData>): UseDataConnectQueryResult<GetReporteCuentasData, GetReporteCuentasVariables>;
export function useGetReporteCuentas(dc: DataConnect, vars: GetReporteCuentasVariables, options?: useDataConnectQueryOptions<GetReporteCuentasData>): UseDataConnectQueryResult<GetReporteCuentasData, GetReporteCuentasVariables>;

export function useGetDetalleReporteCuentas(vars: GetDetalleReporteCuentasVariables, options?: useDataConnectQueryOptions<GetDetalleReporteCuentasData>): UseDataConnectQueryResult<GetDetalleReporteCuentasData, GetDetalleReporteCuentasVariables>;
export function useGetDetalleReporteCuentas(dc: DataConnect, vars: GetDetalleReporteCuentasVariables, options?: useDataConnectQueryOptions<GetDetalleReporteCuentasData>): UseDataConnectQueryResult<GetDetalleReporteCuentasData, GetDetalleReporteCuentasVariables>;

export function useGetFiltrosReportes(vars?: GetFiltrosReportesVariables, options?: useDataConnectQueryOptions<GetFiltrosReportesData>): UseDataConnectQueryResult<GetFiltrosReportesData, GetFiltrosReportesVariables>;
export function useGetFiltrosReportes(dc: DataConnect, vars?: GetFiltrosReportesVariables, options?: useDataConnectQueryOptions<GetFiltrosReportesData>): UseDataConnectQueryResult<GetFiltrosReportesData, GetFiltrosReportesVariables>;

export function useGetSeguimientoPublicoPorQr(vars: GetSeguimientoPublicoPorQrVariables, options?: useDataConnectQueryOptions<GetSeguimientoPublicoPorQrData>): UseDataConnectQueryResult<GetSeguimientoPublicoPorQrData, GetSeguimientoPublicoPorQrVariables>;
export function useGetSeguimientoPublicoPorQr(dc: DataConnect, vars: GetSeguimientoPublicoPorQrVariables, options?: useDataConnectQueryOptions<GetSeguimientoPublicoPorQrData>): UseDataConnectQueryResult<GetSeguimientoPublicoPorQrData, GetSeguimientoPublicoPorQrVariables>;

export function useGetSeguimientoPublicoPorNumero(vars: GetSeguimientoPublicoPorNumeroVariables, options?: useDataConnectQueryOptions<GetSeguimientoPublicoPorNumeroData>): UseDataConnectQueryResult<GetSeguimientoPublicoPorNumeroData, GetSeguimientoPublicoPorNumeroVariables>;
export function useGetSeguimientoPublicoPorNumero(dc: DataConnect, vars: GetSeguimientoPublicoPorNumeroVariables, options?: useDataConnectQueryOptions<GetSeguimientoPublicoPorNumeroData>): UseDataConnectQueryResult<GetSeguimientoPublicoPorNumeroData, GetSeguimientoPublicoPorNumeroVariables>;

export function useGetComandaOperativaPorQr(vars: GetComandaOperativaPorQrVariables, options?: useDataConnectQueryOptions<GetComandaOperativaPorQrData>): UseDataConnectQueryResult<GetComandaOperativaPorQrData, GetComandaOperativaPorQrVariables>;
export function useGetComandaOperativaPorQr(dc: DataConnect, vars: GetComandaOperativaPorQrVariables, options?: useDataConnectQueryOptions<GetComandaOperativaPorQrData>): UseDataConnectQueryResult<GetComandaOperativaPorQrData, GetComandaOperativaPorQrVariables>;
